import 'dart:io';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';


import 'package:tahircoolpointtechnician/authpage.dart';
import 'package:tahircoolpointtechnician/login.dart';

import 'firebase_options.dart'; // Must exist (generated by FlutterFire CLI)


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if(Firebase.apps.isEmpty){
  await Firebase.initializeApp(
    options: const FirebaseOptions(
 apiKey: 'AIzaSyA63Koxo3Ll5q-Z7ONtVOurwPO_L7H6hHk',
    appId: '1:650722845488:web:517001697caecff526def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    authDomain: 'tahircoolpoint-dc3c6.firebaseapp.com',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
          )
  );
  }
  else if (Platform.isAndroid){
     await Firebase.initializeApp(
    options: const FirebaseOptions(
    apiKey: 'AIzaSyAO9fZi2BUEkRcNS12SoheOSL-ALW8K69U',
    appId: '1:650722845488:android:db2b2e97581f083c26def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
          )
  );
  }
  else if (Platform.isIOS)
  {
 await Firebase.initializeApp(
    options: const FirebaseOptions(
    apiKey: 'AIzaSyBanlvqhfNmso4OmjjCTGlggeXVyD6FfdU',
    appId: '1:650722845488:ios:0809caa687d6004026def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
    iosBundleId: 'com.example.tahircoolpoint',
          )
  );
  }
  else if (Platform.isMacOS)
  {
await Firebase.initializeApp(
    options: const FirebaseOptions(
  apiKey: 'AIzaSyBanlvqhfNmso4OmjjCTGlggeXVyD6FfdU',
    appId: '1:650722845488:ios:0809caa687d6004026def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
    iosBundleId: 'com.example.tahircoolpoint',         
     )
  );
  }
  else if (Platform.isWindows)
  {
await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: 'AIzaSyA63Koxo3Ll5q-Z7ONtVOurwPO_L7H6hHk',
    appId: '1:650722845488:web:1cc05b3865509bd626def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    authDomain: 'tahircoolpoint-dc3c6.firebaseapp.com',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
  
          )
  );
  }
  runApp(const MyApp());
}





class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
  debugShowCheckedModeBanner: false,
  initialRoute: '/',
  routes: {
      '/': (context) => SplashScreen(),
  '/auth': (context) => AuthPage(),
  '/login' : (context) => LoginPage()

 
 


  




    
    
  },
);

  }
}




  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      home: SplashScreen(),
    );
  }


class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  _SplashScreenState createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _scaleAnimation;
  late Animation<double> _fadeAnimation;
  bool _animationCompleted = false;

  @override
  void initState() {
    super.initState();

    _animationController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 3),
    );

    _scaleAnimation = TweenSequence<double>([
      TweenSequenceItem(tween: Tween<double>(begin: 0.7, end: 1.1), weight: 50),
      TweenSequenceItem(tween: Tween<double>(begin: 1.1, end: 1.0), weight: 50),
    ]).animate(_animationController);

    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(
        parent: _animationController,
        curve: Curves.easeInOut,
      ),
    );

    _animationController.forward().whenComplete(() {
      setState(() {
        _animationCompleted = true;
      });
      Future.delayed(const Duration(seconds: 1), () {
        Get.offNamed('/login');
      });
    });
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        fit: StackFit.expand,
        children: [
          ColorFiltered(
            colorFilter: ColorFilter.mode(
              Colors.black.withOpacity(0.2),
              BlendMode.darken,
            ),
            child: Image.asset(
              'images/bg.png',
              fit: BoxFit.cover,
            ),
          ),
          BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
            child: Container(
              color: Colors.black.withOpacity(0.1),
            ),
          ),
          Center(
            child: AnimatedBuilder(
              animation: _animationController,
              builder: (context, child) {
                return Transform.scale(
                  scale: _scaleAnimation.value,
                  child: Opacity(
                    opacity: _fadeAnimation.value,
                    child: Image.asset(
                      'images/icon.png',
                      width: 150,
                      height: 150,
                    ),
                  ),
                );
              },
            ),
          ),
          if (_animationCompleted)
            Positioned(
              bottom: 50,
              left: 0,
              right: 0,
              child: Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                ),
              ),
            ),
        ],
      ),
  
    );
    
  }

}
