import 'dart:io';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:tahircoolpointtechnician/SplashScreen.dart';


import 'package:tahircoolpointtechnician/authpage.dart';
import 'package:tahircoolpointtechnician/home.dart';
import 'package:tahircoolpointtechnician/login.dart';
import 'package:tahircoolpointtechnician/order.dart';
import 'package:tahircoolpointtechnician/profile.dart';

import 'firebase_options.dart'; // Must exist (generated by FlutterFire CLI)


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if(Firebase.apps.isEmpty){
  await Firebase.initializeApp(
    options: const FirebaseOptions(
 apiKey: 'AIzaSyA63Koxo3Ll5q-Z7ONtVOurwPO_L7H6hHk',
    appId: '1:650722845488:web:517001697caecff526def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    authDomain: 'tahircoolpoint-dc3c6.firebaseapp.com',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
          )
  );
  }
  else if (Platform.isAndroid){
     await Firebase.initializeApp(
    options: const FirebaseOptions(
    apiKey: 'AIzaSyAO9fZi2BUEkRcNS12SoheOSL-ALW8K69U',
    appId: '1:650722845488:android:db2b2e97581f083c26def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
          )
  );
  }
  else if (Platform.isIOS)
  {
 await Firebase.initializeApp(
    options: const FirebaseOptions(
    apiKey: 'AIzaSyBanlvqhfNmso4OmjjCTGlggeXVyD6FfdU',
    appId: '1:650722845488:ios:0809caa687d6004026def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
    iosBundleId: 'com.example.tahircoolpoint',
          )
  );
  }
  else if (Platform.isMacOS)
  {
await Firebase.initializeApp(
    options: const FirebaseOptions(
  apiKey: 'AIzaSyBanlvqhfNmso4OmjjCTGlggeXVyD6FfdU',
    appId: '1:650722845488:ios:0809caa687d6004026def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
    iosBundleId: 'com.example.tahircoolpoint',         
     )
  );
  }
  else if (Platform.isWindows)
  {
await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: 'AIzaSyA63Koxo3Ll5q-Z7ONtVOurwPO_L7H6hHk',
    appId: '1:650722845488:web:1cc05b3865509bd626def5',
    messagingSenderId: '650722845488',
    projectId: 'tahircoolpoint-dc3c6',
    authDomain: 'tahircoolpoint-dc3c6.firebaseapp.com',
    storageBucket: 'tahircoolpoint-dc3c6.firebasestorage.app',
  
          )
  );
  }
  runApp(const MyApp());
}





class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
  debugShowCheckedModeBanner: false,
  initialRoute: '/',
 onGenerateRoute: (settings) {
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(builder: (_) => SplashScreen());
              case '/auth':
        return MaterialPageRoute(builder: (_) => AuthPage());

      case '/login':
        return MaterialPageRoute(builder: (_) => LoginPage());
              case '/home':
        return MaterialPageRoute(builder: (_) => HomePage());

      case '/profile':
        return MaterialPageRoute(builder: (_) => ProfilePage());
        case '/order':
        return MaterialPageRoute(builder: (_) => OrderPage());
      default:
        return MaterialPageRoute(builder: (_) => LoginPage());
    }
  },
    );
  }
}